name: Update Monkeytype Stats

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 */12 * * *' # every 12 hours

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch Monkeytype data
        env:
          MONKEYTYPE_API_KEY: ${{ secrets.MONKEYTYPE_API_KEY }}
          MONKEYTYPE_OUT_PATH: monkeytype.json
          MONKEYTYPE_USERNAME: ${{ vars.MONKEYTYPE_USERNAME || 'rizkyilhampra' }}
        run: |
          if ! node scripts/fetch-monkeytype.mjs; then
            echo "Failed to fetch Monkeytype data"
            exit 1
          fi

      - name: Verify changes
        id: verify
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            # Only check monkeytype.json was modified
            if git diff --name-only | grep -q '^monkeytype\.json$'; then
              echo "Monkeytype data updated"
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "Unexpected file changes detected"
              git diff --name-only
              exit 1
            fi
          fi

      - name: Commit and push if changed
        if: steps.verify.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add monkeytype.json
          git commit -m "chore(monkeytype): update stats [skip ci]"
          git push
